import {
  Combine,
  Minimize2,
  Scissors,
  FileText,
  FileUp,
  Image as ImageIcon,
  RotateCw,
  FileKey,
} from "lucide-react";

export const PDF_TOOLS = Object.freeze([
  {
    id: "pdf-merge",
    title: "Merge PDF",
    description: "Combine PDFs",
    href: "/dashboard/pdf-merge",
    icon: Combine,
  },
  {
    id: "document-to-pdf",
    title: "Document to PDF",
    description: "Convert documents to PDF",
    href: "/dashboard/document-to-pdf",
    icon: FileText,
  },
  {
    id: "jpeg-to-pdf",
    title: "JPEG to PDF",
    description: "Convert JPEG images into PDF",
    href: "/tool/jpeg-to-pdf",
    icon: ImageIcon,
  },
  {
    id: "png-to-pdf",
    title: "PNG to PDF",
    description: "Convert PNG images into PDF",
    href: "/tool/png-to-pdf",
    icon: ImageIcon,
  },
  {
    id: "pdf-compress",
    title: "Compress PDF",
    description: "Reduce file size",
    href: "/tool/pdf-compress",
    icon: Minimize2,
  },
  {
    id: "pdf-split",
    title: "Split PDF",
    description: "Split pages",
    href: "/dashboard/pdf-split",
    icon: Scissors,
  },
  {
    id: "pdf-protect",
    title: "Protect PDF",
    description: "Add password protection",
    href: "/tool/pdf-protect",
    icon: FileText,
  },
  {
    id: "pdf-redact",
    title: "Redact PDF",
    description: "Remove sensitive information",
    href: "/tool/pdf-redact",
    icon: FileUp,
  },
  {
    id: "metadata-viewer",
    title: "Metadata Viewer",
    description: "View PDF metadata details",
    href: "/tool/metadata-viewer",
    icon: FileText,
  },
  {
    id: "pdf-watermark",
    title: "Watermark PDF",
    description: "Add text watermark to PDF files",
    href: "/tool/pdf-watermark",
    icon: FileText,
  },
  {
    id: "pdf-page-numbers",
    title: "Add Page Numbers",
    description: "Insert page numbers into PDF",
    href: "/tool/pdf-page-numbers",
    icon: FileText,
  },
  {
    id: "pdf-extract-images",
    title: "Extract Images",
    description: "Extract embedded images from PDF",
    href: "/tool/pdf-extract-images",
    icon: ImageIcon,
  },
  {
    id: "pdf-rotate",
    title: "Rotate PDF",
    description: "Rotate PDF pages",
    href: "/tool/pdf-rotate",
    icon: RotateCw,
  },
  {
    id: "pdf-delete-pages",
    title: "Delete PDF Pages",
    description: "Remove selected pages from PDF",
    href: "/tool/pdf-delete-pages",
    icon: Scissors,
  },
  {
    id: "pdf-page-reorder",
    title: "Reorder PDF Pages",
    description: "Drag and reorder PDF pages",
    href: "/tool/pdf-page-reorder",
    icon: Scissors,
  },
  {
    id: "pdf-password-remover",
    title: "PDF Password Remover",
    description: "Remove password from protected PDF files",
    href: "/tool/pdf-password-remover",
    icon: FileKey,
  },
]);
